-- =====================================================
-- ESTRUTURA INICIAL DO BANCO DE DADOS
-- =====================================================

-- A tabela categoria foi criada anteriormente na migration V1.
-- Ela armazena os tipos de equipamentos, como:
-- Notebook, Chromebook, Desktop e Tablet.
-- Não é criada novamente neste arquivo.

-- =====================================================
-- TABELA FABRICANTE
-- Armazena os fabricantes dos equipamentos
-- Exemplos: Positivo, Samsung e Lenovo
-- =====================================================
CREATE TABLE fabricante (
    -- Identificador único gerado automaticamente
    id_fabricante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome obrigatório e não repetido do fabricante
    nome VARCHAR(100) NOT NULL UNIQUE,

    -- Indica se o fabricante está disponível no sistema
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- TABELA LOCALIZACAO
-- Armazena os locais onde os equipamentos ficam
-- Exemplos de códigos: C3, C4, CHL e CHI
-- =====================================================
CREATE TABLE localizacao (

    -- Identificador único gerado automaticamente
    id_localizacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Código obrigatório e não repetido da localização
    codigo VARCHAR(20) NOT NULL UNIQUE,

    -- Nome obrigatório da localização
    nome VARCHAR(100) NOT NULL,

    -- Informações adicionais opcionais
    descricao TEXT,

    -- Indica se a localização está disponível no sistema
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- TABELA MODELO
-- Armazena os modelos e os relaciona a um fabricante
-- e a uma categoria
-- Exemplos: N1110, N1210 e XE310XDA
-- =====================================================
CREATE TABLE modelo (

    -- Identificador único gerado automaticamente
    id_modelo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Nome obrigatório do modelo
    nome VARCHAR(100) NOT NULL,

    -- Identificador do fabricante ao qual o modelo pertence
    id_fabricante BIGINT NOT NULL,

    -- Identificador da categoria à qual o modelo pertence
    id_categoria BIGINT NOT NULL,

    -- Indica se o modelo está disponível no sistema
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    -- Garante que o fabricante informado exista
    CONSTRAINT fk_modelo_fabricante
        FOREIGN KEY (id_fabricante)
        REFERENCES fabricante (id_fabricante),

    -- Garante que a categoria informada exista
    CONSTRAINT fk_modelo_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria (id_categoria),

    -- Impede repetir a mesma combinação de modelo,
    -- fabricante e categoria
    CONSTRAINT uk_modelo_nome_fabricante_categoria
        UNIQUE (nome, id_fabricante, id_categoria)
);

-- =====================================================
-- TABELA EQUIPAMENTO
-- Armazena os equipamentos cadastrados no inventário
-- Exemplos de identificadores: C3-002, C4-015 e CHL-008
-- =====================================================
CREATE TABLE equipamento (
    id_equipamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Código usado pela escola, como C3-002
    identificador_interno VARCHAR(20) NOT NULL UNIQUE,

    -- Número de série fornecido pelo fabricante
    numero_serie VARCHAR(100) NOT NULL UNIQUE,

    -- Modelo do equipamento
    id_modelo BIGINT NOT NULL,

    -- Localização atual do equipamento
    id_localizacao BIGINT NOT NULL,

    -- Estado atual: OK, ATENCAO ou CRITICO
    status_funcionamento VARCHAR(30) NOT NULL,

    -- Data em que o equipamento foi cadastrado
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Data da última atualização
    data_atualizacao DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Informações adicionais opcionais
    observacoes TEXT,

    -- Indica se o equipamento está ativo no sistema
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    -- Garante que o modelo informado exista
    CONSTRAINT fk_equipamento_modelo
        FOREIGN KEY (id_modelo)
        REFERENCES modelo (id_modelo),

    -- Garante que a localização informada exista
    CONSTRAINT fk_equipamento_localizacao
        FOREIGN KEY (id_localizacao)
        REFERENCES localizacao (id_localizacao)
);